import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { setup as setupDesktop } from './desktop-fixture.mjs'

const fixtures = JSON.parse(readFileSync(new URL('../.validation/fixtures.json', import.meta.url), 'utf8'))
const setup = page => setupDesktop(page, fixtures)

const nav = (page, name) => page.getByRole('navigation', { name: 'Hauptnavigation' }).getByRole('button', { name, exact: true })
test('backend contexts and compact deltas', async ({ page }) => {
  test.skip(!fixtures.overview.comparisons, 'Requires the separate analytics contract fixture')
  await offline(page)
  const current = page.locator('.kpi-row .metric-card').filter({ has: page.getByText('Aktuell offen', { exact: true }) })
  await expect(current.getByText(fixtures.overview.metrics.at(-1).contextLabel, { exact: true })).toBeVisible()
  const closed = page.locator('.kpi-row .metric-card').filter({ has: page.getByText('Geschlossene Tickets', { exact: true }) })
  await expect(closed.locator('.metric-trend.improvement')).toBeVisible()
  const service = page.locator('.service-card')
  await service.getByText('Durchschnitt anzeigen').first().click()
  await expect(service.getByText(/^Durchschnitt:/).first()).toBeVisible()
})
test('honest historical snapshot', async ({ page }) => {
  test.skip(!fixtures.historicalOverview, 'Requires the separate analytics contract fixture')
  await setupDesktop(page, { ...fixtures, overview: fixtures.historicalOverview })
  await page.getByRole('button', { name: 'Lokalen Datenstand öffnen' }).click()
  const historical = page.locator('.kpi-row .metric-card').filter({ has: page.getByText('Aktuell offen', { exact: true }) })
  await expect(historical.getByText(/^Stand am /)).toBeVisible()
  await expect(historical.locator('strong')).toHaveText('–')
  await expect(historical.locator('.metric-trend')).toHaveCount(0)
})
test('login contrast and shared theme before and after authentication', async ({ page }) => {
  await setupDesktop(page, { ...fixtures, initialTheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.getByRole('heading', { name: 'Willkommen zurück.' })).toHaveCSS('color', 'rgb(32, 42, 55)')
  await expect(page.getByLabel('Benutzername', { exact: true })).toHaveCSS('color', 'rgb(32, 42, 55)')
  await page.getByRole('button', { name: 'Helles oder dunkles Design' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('heading', { name: 'Willkommen zurück.' })).toHaveCSS('color', 'rgb(244, 247, 250)')
  await page.getByRole('button', { name: 'Lokalen Datenstand öffnen' }).click()
  await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})
async function offline(page) { await setup(page); await page.getByRole('button', { name: 'Lokalen Datenstand öffnen' }).click(); await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible() }
async function login(page) {
  await page.getByLabel('Benutzername', { exact: true }).fill('validation')
  await page.getByLabel('Passwort', { exact: true }).fill('validation')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Aktualisieren', exact: true })).toBeEnabled()
}
test('range and logout confirmations preserve current data until approved', async ({ page }) => {
  await setup(page); await login(page)
  const calls = await page.evaluate(() => window.validation.calls.filter(call => call.name === 'refresh').length)
  await page.locator('.timeline-labels').getByRole('button', { name: '1M', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Längerer Zeitraum')).toBeVisible()
  expect(await page.evaluate(() => window.validation.calls.filter(call => call.name === 'refresh').length)).toBe(calls)
  await page.getByRole('button', { name: 'Abbrechen', exact: true }).click()
  await expect(page.getByRole('slider', { name: 'Zeitraum-Beginn' })).toHaveAttribute('aria-valuetext', '1W')
  await page.locator('.timeline-labels').getByRole('button', { name: '1M', exact: true }).click()
  await page.getByRole('button', { name: 'Laden', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.validation.calls.filter(call => call.name === 'refresh').length)).toBe(calls + 1)
  await page.getByRole('button', { name: 'Logout', exact: true }).click()
  expect(await page.evaluate(() => window.validation.calls.filter(call => call.name === 'logout').length)).toBe(0)
  await page.getByRole('button', { name: 'Abbrechen', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible()
  await page.getByRole('button', { name: 'Logout', exact: true }).click()
  await page.getByRole('button', { name: 'Ausloggen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Anmelden', exact: true })).toBeVisible()
})
test('custom long range, connection tooltip and optional new-data refresh', async ({ page }) => {
  await page.clock.install()
  await setupDesktop(page, { ...fixtures, custom: fixtures.longCustom }); await login(page)
  await page.getByLabel('Von', { exact: true }).fill(fixtures.longCustom.startInput)
  await page.getByLabel('Bis', { exact: true }).fill(fixtures.longCustom.endInput)
  await page.getByRole('button', { name: 'Anwenden' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Abbrechen', exact: true }).click()
  await page.locator('.tooltip-trigger').focus()
  await expect(page.getByRole('tooltip')).toContainText('08.10.2026 10:23:45')
  await page.locator('.tooltip-trigger').hover()
  await expect(page.getByRole('tooltip')).toBeVisible()
  const calls = await page.evaluate(() => window.validation.calls.filter(call => call.name === 'refresh').length)
  await page.clock.fastForward(120001)
  await expect(page.getByText('Neue Daten verfügbar', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.validation.calls.filter(call => call.name === 'refresh').length)).toBe(calls)
  await page.getByRole('button', { name: 'Aktualisieren', exact: true }).click()
  await expect(page.getByText('Neue Daten verfügbar', { exact: true })).not.toBeVisible()
})
test('system reduced motion overrides locally enabled chart and CSS animations', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await offline(page)
  await expect(page.getByRole('button', { name: 'Animationen', exact: true })).toBeDisabled()
  await expect(page.locator('html')).toHaveAttribute('data-reduced-motion', 'true')
  if (fixtures.overview.comparisons) await expect(page.locator('.metric-trend').first()).toHaveCSS('animation-name', 'none')
})

test('cached dashboard and complete navigation, ticket, team, export and logout', async ({ page }, info) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await offline(page)
  await expect(page.getByText('Lokaler Datenstand', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `.validation/overview-${info.project.name}.png`, fullPage: true })
  if (info.project.name === 'desktop-1920') expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(1080)
  await nav(page, 'Analysen').click()
  for (const [index, data] of Object.entries(fixtures.analyses)) {
    await page.getByRole('tab').nth(Number(index) - 1).click()
    await expect(page.getByRole('heading', { name: data.all.title, exact: true }).first()).toBeVisible()
  }
  await page.getByRole('tab').nth(4).click()
  await page.getByLabel('Tickettyp', { exact: true }).selectOption('Auftrag')
  await expect.poll(() => page.evaluate(() => window.validation.calls.filter(call => call.name === 'getAnalysis').at(-1).args)).toEqual([5, 'Auftrag', 0])
  await page.screenshot({ path: `.validation/analysis-${info.project.name}.png`, fullPage: true })
  await nav(page, 'Agenten').click()
  await expect(page.getByText('Informelles Ranking', { exact: true })).toBeVisible()
  await page.screenshot({ path: `.validation/agents-${info.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Team verwalten' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('dialog').getByRole('checkbox').last().check()
  await page.getByRole('button', { name: 'Speichern', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await nav(page, 'Übersicht').click()
  const cachedCalls = await page.evaluate(() => window.validation.calls.filter(call => call.name === 'getOverview').length)
  await nav(page, 'Info').click()
  await page.getByRole('button', { name: 'Animationen', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-reduced-motion', 'true')
  await nav(page, 'Übersicht').click()
  expect(await page.evaluate(() => window.validation.calls.filter(call => call.name === 'getOverview').length)).toBe(cachedCalls)
  await page.getByRole('button', { name: /^TEST/ }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText('Kundennummer', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: /In Znuny/ }).click()
  await expect.poll(() => page.evaluate(() => window.validation.calls.some(call => call.name === 'openTicket'))).toBe(true)
  await page.getByRole('dialog').getByRole('button', { name: 'Schliessen' }).first().click()
  await page.getByRole('button', { name: 'Helles oder dunkles Design' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.screenshot({ path: `.validation/light-${info.project.name}.png`, fullPage: true })
  await nav(page, 'Export').click()
  await page.getByLabel('Auswertung', { exact: true }).selectOption('5')
  await page.getByLabel('Tickettyp im Export', { exact: true }).selectOption('Auftrag')
  await page.getByRole('button', { name: 'Als PDF speichern' }).click()
  await expect(page.getByRole('status')).toHaveText('PDF gespeichert: synthetic-report.pdf')
  expect(await page.evaluate(() => window.validation.calls.filter(call => call.name === 'exportPdf').at(-1).args)).toEqual(['5', 'Auftrag'])
  await page.getByRole('button', { name: 'Logout', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Möchtest du dich wirklich ausloggen?')).toBeVisible()
  await page.getByRole('button', { name: 'Ausloggen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Anmelden', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('backend winners and persistent local identity editor', async ({ page }, info) => {
  test.skip(!fixtures.agents.periodWinners, 'Requires agent analytics contract')
  await offline(page); await nav(page, 'Agenten').click()
  const employee = page.locator('.agents-employee')
  await expect(employee.getByRole('heading', { name: 'Mitarbeiter des Zeitraums' })).toBeVisible()
  await expect(employee.locator('article')).toHaveCount(fixtures.agents.periodWinners.filter(row => row.isPeriodWinner).length)
  await expect(employee.getByText('0 min', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Team verwalten' }).click()
  const row = page.locator('.team-identity').first()
  await expect(row.getByText(/Quelle:/)).toBeVisible()
  await row.getByRole('button', { name: 'Bearbeiten', exact: true }).click()
  await row.getByLabel('Anzeigename', { exact: true }).fill('Lokaler Testname')
  await row.getByLabel('Kürzel', { exact: true }).fill('LTN')
  await row.getByRole('button', { name: 'Änderung speichern' }).click()
  await expect(row.locator('label>span').first()).toContainText('Lokaler Testname')
  await expect.poll(() => page.evaluate(() => window.validation.calls.some(call => call.name === 'setAgentAbbreviation' && call.args[1] === 'LTN'))).toBe(true)
  await row.getByRole('button', { name: 'Zurücksetzen auf automatisch' }).click()
  await expect(row.locator('label>span').first()).not.toContainText('Lokaler Testname')
  await page.screenshot({ path: `.validation/team-${info.project.name}.png`, fullPage: true })
  await page.getByRole('dialog').getByRole('button', { name: 'Schliessen', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('login errors, custom interval, handle snap, cached refresh and pending navigation', async ({ page }) => {
  await setup(page)
  await page.getByLabel('Benutzername', { exact: true }).fill('wrong')
  await page.getByLabel('Passwort', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Anmeldung fehlgeschlagen.')
  await expect(page.getByLabel('Passwort', { exact: true })).toHaveValue('')
  await page.getByLabel('Benutzername', { exact: true }).fill('network-error')
  await page.getByLabel('Passwort', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Znuny ist nicht erreichbar.')
  await page.getByLabel('Benutzername', { exact: true }).fill('validation')
  await page.getByLabel('Passwort', { exact: true }).fill('validation')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible()
  await page.getByLabel('Von', { exact: true }).fill(fixtures.custom.startInput)
  await page.getByLabel('Bis', { exact: true }).fill(fixtures.custom.endInput)
  await page.getByRole('button', { name: 'Anwenden' }).click()
  await expect(page.locator('.custom-labels')).toBeVisible()
  await expect(page.locator('.timeline-selected')).toHaveCSS('left', '0px')
  await page.getByRole('slider', { name: 'Zeitraum-Beginn' }).press('End')
  await expect(page.getByRole('slider', { name: 'Zeitraum-Beginn' })).toHaveAttribute('aria-valuetext', '1T')
  await page.evaluate(() => { window.validation.refreshDelay = 1400; window.validation.failRefresh = true })
  await page.getByRole('button', { name: 'Aktualisieren', exact: true }).click()
  await expect(page.getByText('Znuny-Daten werden geladen …', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible()
  await nav(page, 'Agenten').click()
  await expect(page.getByText('Informelles Ranking', { exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Sitzung ist abgelaufen')
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
})
