import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { setup as setupDesktop } from './desktop-fixture.mjs'

const fixtures = JSON.parse(readFileSync(new URL('../.validation/fixtures.json', import.meta.url), 'utf8'))
const setup = page => setupDesktop(page, fixtures)

const nav = (page, name) => page.getByRole('navigation', { name: 'Hauptnavigation' }).getByRole('button', { name, exact: true })
test('login contrast and shared theme before and after authentication', async ({ page }) => {
  await setupDesktop(page, { ...fixtures, initialTheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.getByRole('heading', { name: 'Willkommen zurück.' })).toHaveCSS('color', 'rgb(32, 42, 55)')
  await expect(page.getByLabel('Benutzername', { exact: true })).toHaveCSS('color', 'rgb(32, 42, 55)')
  await page.getByRole('button', { name: 'Helles oder dunkles Design' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('heading', { name: 'Willkommen zurück.' })).toHaveCSS('color', 'rgb(244, 247, 250)')
  await page.getByRole('button', { name: 'Lokalen Datenstand öffnen' }).click()
  await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})
async function offline(page) { await setup(page); await page.getByRole('button', { name: 'Lokalen Datenstand öffnen' }).click(); await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible() }

test('cached dashboard and complete navigation, ticket, team, export and logout', async ({ page }, info) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await offline(page)
  await expect(page.getByText('Lokaler Datenstand', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `.validation/overview-${info.project.name}.png`, fullPage: true })
  if (info.project.name === 'desktop-1920') expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(1080)
  await nav(page, 'Analysen').click()
  for (const [index, data] of Object.entries(fixtures.analyses)) {
    await page.getByRole('tab').nth(Number(index) - 1).click()
    await expect(page.getByRole('heading', { name: data.all.title, exact: true }).first()).toBeVisible()
  }
  await page.getByRole('tab').nth(4).click()
  await page.getByLabel('Tickettyp', { exact: true }).selectOption('Auftrag')
  await expect.poll(() => page.evaluate(() => window.validation.calls.filter(call => call.name === 'getAnalysis').at(-1).args)).toEqual([5, 'Auftrag', 0])
  await page.screenshot({ path: `.validation/analysis-${info.project.name}.png`, fullPage: true })
  await nav(page, 'Agenten').click()
  await expect(page.getByText('Informelles Ranking', { exact: true })).toBeVisible()
  await page.screenshot({ path: `.validation/agents-${info.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Team verwalten' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('dialog').getByRole('checkbox').last().check()
  await page.getByRole('button', { name: 'Speichern', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await nav(page, 'Übersicht').click()
  const cachedCalls = await page.evaluate(() => window.validation.calls.filter(call => call.name === 'getOverview').length)
  await nav(page, 'Info').click()
  await page.getByRole('checkbox', { name: /Bewegungen reduzieren/ }).check()
  await expect(page.locator('html')).toHaveAttribute('data-reduced-motion', 'true')
  await nav(page, 'Übersicht').click()
  expect(await page.evaluate(() => window.validation.calls.filter(call => call.name === 'getOverview').length)).toBe(cachedCalls)
  await page.getByRole('button', { name: /^TEST/ }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText('Kundennummer', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: /In Znuny/ }).click()
  await expect.poll(() => page.evaluate(() => window.validation.calls.some(call => call.name === 'openTicket'))).toBe(true)
  await page.getByRole('dialog').getByRole('button', { name: 'Schliessen' }).first().click()
  await page.getByRole('button', { name: 'Helles oder dunkles Design' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.screenshot({ path: `.validation/light-${info.project.name}.png`, fullPage: true })
  await nav(page, 'Export').click()
  await page.getByLabel('Auswertung', { exact: true }).selectOption('5')
  await page.getByLabel('Tickettyp im Export', { exact: true }).selectOption('Auftrag')
  await page.getByRole('button', { name: 'Als PDF speichern' }).click()
  await expect(page.getByRole('status')).toHaveText('PDF gespeichert: synthetic-report.pdf')
  expect(await page.evaluate(() => window.validation.calls.filter(call => call.name === 'exportPdf').at(-1).args)).toEqual(['5', 'Auftrag'])
  await page.getByRole('button', { name: 'Logout', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Anmelden', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('login errors, custom interval, handle snap, cached refresh and pending navigation', async ({ page }) => {
  await setup(page)
  await page.getByLabel('Benutzername', { exact: true }).fill('wrong')
  await page.getByLabel('Passwort', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Anmeldung fehlgeschlagen.')
  await expect(page.getByLabel('Passwort', { exact: true })).toHaveValue('')
  await page.getByLabel('Benutzername', { exact: true }).fill('network-error')
  await page.getByLabel('Passwort', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Znuny ist nicht erreichbar.')
  await page.getByLabel('Benutzername', { exact: true }).fill('validation')
  await page.getByLabel('Passwort', { exact: true }).fill('validation')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible()
  await page.getByLabel('Von', { exact: true }).fill(fixtures.custom.startInput)
  await page.getByLabel('Bis', { exact: true }).fill(fixtures.custom.endInput)
  await page.getByRole('button', { name: 'Anwenden' }).click()
  await expect(page.locator('.custom-labels')).toBeVisible()
  await expect(page.locator('.timeline-selected')).toHaveCSS('left', '0px')
  await page.getByRole('slider', { name: 'Zeitraum-Beginn' }).press('End')
  await expect(page.getByRole('slider', { name: 'Zeitraum-Beginn' })).toHaveAttribute('aria-valuetext', '1T')
  await page.evaluate(() => { window.validation.refreshDelay = 1400; window.validation.failRefresh = true })
  await page.getByRole('button', { name: 'Aktualisieren', exact: true }).click()
  await expect(page.getByText('Znuny-Daten werden geladen …', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Ticketentwicklung' })).toBeVisible()
  await nav(page, 'Agenten').click()
  await expect(page.getByText('Informelles Ranking', { exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Sitzung ist abgelaufen')
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
})
